#pragma once
#include <iostream>
#include <string>
#include <string_view>
#include <vector>
#include <array>
#include <list>
#include <algorithm>
#include <ranges>
#include <cassert>
#include <unordered_map>
#include <map>
#include <sstream>
#include <iomanip>
#include <exception>
#include <queue>
#include <deque>
#include <bitset>
#include <chrono>
#include <optional>
#include <memory>
#include <thread>

#include <wrl/client.h>
#include <d3d11.h>
#include <d3dcompiler.h>

#define WIN32_LEAN_AND_MEAN
#define NOGDICAPMASKS
#define NOSYSMETRICS
#define NOMENUS
#define NOICONS
#define NOSYSCOMMANDS
#define NORASTEROPS
#define OEMRESOURCE
#define NOATOM
#define NOCLIPBOARD
#define NOCOLOR
#define NOCTLMGR
#define NODRAWTEXT
#define NOKERNEL
#define NONLS
#define NOMEMMGR
#define NOMETAFILE
#define NOMINMAX
#define NOOPENFILE
#define NOSCROLL
#define NOSERVICE
#define NOSOUND
#define NOTEXTMETRIC
#define NOWH
#define NOCOMM
#define NOKANJI
#define NOHELP
#define NOPROFILER
#define NODEFERWINDOWPOS
#define NOMCX
#define NORPC
#define NOPROXYSTUB
#define NOIMAGE
#define NOTAPE

#include <Windows.h>